---

- name: NODE_EXPORTER | Configuring service
  systemd:
    name: node_exporter
    state: "{{ node_exporter_service_state }}"
    enabled: "{{ node_exporter_service_enabled }}"
    daemon_reload: true
  when: node_exporter_manage_service

- name: NODE_EXPORTER | Restart if necessary
  meta: flush_handlers

- name: NODE_EXPORTER | Wait for service listening
  wait_for:
    host: "{{ node_exporter_host_name }}"
    port: "{{ node_exporter_port }}"
    state: "{{ node_exporter_service_state }}"
    delay: 5
    timeout: 300
  when:
    - node_exporter_service_enabled
    - node_exporter_service_state in ["started","restarted"]
