---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: installing test required libs
      apt:
        pkg: "{{ item }}"
        state: present
      with_items:
        - net-tools
        - netcat